import type { Metadata } from "next";
import { Figtree } from 'next/font/google';
import "./globals.css";
import {PublicEnvScript} from "next-runtime-env";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const figtree = Figtree({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-figtree'
})

export const metadata: Metadata = {
  title: "Palette",
  description: "Generated by create next app",
  icons: {
    icon: '/images/favicon.ico',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PublicEnvScript/>
      </head>
      <body className={`${figtree.className}`}>
        {children}
      </body>
    </html>
  );
}
